name: AWS Credentials Management

on:
  schedule:
    - cron: '0 */6 * * *' # Ejecutar cada 6 horas
  workflow_dispatch: # Permitir ejecución manual

  push:
    branches:
      - develop

jobs:
  get-aws-credentials:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configurar AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
        aws-region: eu-west-3

    - name: Asumir Rol AWS y Obtener Credenciales Temporales
      id: assume-role
      run: |
        CREDS=$(aws sts assume-role --role-arn "arn:aws:iam::248189943700:role/AWSReservedSSO_EKS-alumnos_a4561514b13725b0" --role-session-name "github-actions" --query 'Credentials' --output json)
        echo "AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r '.AccessKeyId')" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r '.SecretAccessKey')" >> $GITHUB_ENV
        echo "AWS_SESSION_TOKEN=$(echo $CREDS | jq -r '.SessionToken')" >> $GITHUB_ENV

    - name: Configurar AWS Credenciales
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
        aws-region: eu-west-3

    - name: Guardar Credenciales en Secretos de GitHub
      run: |
        curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             -d "{\"encrypted_value\":\"${{ env.AWS_ACCESS_KEY_ID }}\",\"key_id\":\"$(echo ${{ secrets.GITHUB_PUBLIC_KEY }} | jq -r '.key_id')\"}" \
             https://api.github.com/repos/${{ github.repository }}/actions/secrets/AWS_ACCESS_KEY_ID

        curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             -d "{\"encrypted_value\":\"${{ env.AWS_SECRET_ACCESS_KEY }}\",\"key_id\":\"$(echo ${{ secrets.GITHUB_PUBLIC_KEY }} | jq -r '.key_id')\"}" \
             https://api.github.com/repos/${{ github.repository }}/actions/secrets/AWS_SECRET_ACCESS_KEY

        curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             -d "{\"encrypted_value\":\"${{ env.AWS_SESSION_TOKEN }}\",\"key_id\":\"$(echo ${{ secrets.GITHUB_PUBLIC_KEY }} | jq -r '.key_id')\"}" \
             https://api.github.com/repos/${{ github.repository }}/actions/secrets/AWS_SESSION_TOKEN
