name: AWS SSO Authentication

on: [push]

jobs:
  authenticate-and-use-aws:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configurar AWS CLI
      run: |
        mkdir -p ~/.aws
        echo "[profile sso-profile]" > ~/.aws/config
        echo "sso_start_url = https://d-8067060d87.awsapps.com/start/#" >> ~/.aws/config
        echo "sso_region = eu-west-3" >> ~/.aws/config
        echo "sso_account_id = 248189943700" >> ~/.aws/config
        echo "sso_role_name = EKS-alumnos" >> ~/.aws/config
        echo "region = eu-west-3" >> ~/.aws/config

    - name: Autenticar con AWS SSO
      run: aws sso login --profile sso-profile

    - name: Configurar Credenciales Temporales
      run: |
        CREDENTIALS=$(aws sso get-role-credentials --profile sso-profile --role-name <tu-role-name> --account-id <tu-account-id> --output json)
        echo $CREDENTIALS
        echo "AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r .roleCredentials.accessKeyId)" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r .roleCredentials.secretAccessKey)" >> $GITHUB_ENV
        echo "AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r .roleCredentials.sessionToken)" >> $GITHUB_ENV

    - name: Usar AWS CLI con Credenciales Temporales
      run: aws s3 ls
