name: Synchronize Secrets

on:
  push:
    branches:
      - develop

jobs:
  synchronize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install awscli

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Sync Variables and Secrets
        run: |
          # Loop through all repository secrets
          for SECRET_NAME in $(echo "$SECRETS_JSON" | jq -r 'keys[] | select(. | startswith("${{ env.ANCHOR_PREFIX }}"))'); do
            NEW_SECRET_NAME_LOWERCASE=$(echo "$SECRET_NAME" | tr '[:upper:]' '[:lower:]')
            SECRET_VALUE=$(echo "$SECRETS_JSON" | jq -r .${SECRET_NAME})
            PARAM_NAME="${NEW_SECRET_NAME_LOWERCASE//_//}"
            aws ssm put-parameter --name "$PARAM_NAME" --value "$SECRET_VALUE" --type SecureString --overwrite
          done

          # Loop through all repository variables
          for VAR_NAME in $(echo "$VARS_JSON" | jq -r 'keys[] | select(. | startswith("${{ env.ANCHOR_PREFIX }}"))'); do
            NEW_VAR_NAME_LOWERCASE=$(echo "$VAR_NAME" | tr '[:upper:]' '[:lower:]')
            VAR_VALUE=$(echo "$VARS_JSON" | jq -r .${VAR_NAME})
            PARAM_NAME="${NEW_VAR_NAME_LOWERCASE//_//}"
            aws ssm put-parameter --name "$PARAM_NAME" --value "$VAR_VALUE" --type String --overwrite

